apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-server-data-pvc
  namespace: {{namespace}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage-sc