site_name: 'KX.AS.CODE'
repo_url: 'https://github.com/Accenture/kx.as.code'
repo_name: 'Github'
site_description: 'KX.AS.CODE'
site_author: 'Patrick Delamere'

docs_dir: docs

nav:
    - 'README.md'
    - 'Quick-Start-Guide.md'
    - 'Overview':
        - 'Overview/Architecture.md'
        - 'Overview/Application-Library.md'
        - 'Overview/Concepts.md'
        - 'Overview/Future-Roadmap.md'
        - 'Overview/Questions-and-Answers.md'
        - 'Overview/Raising-a-Bug-Report.md'
        - 'Overview/Raising-a-Feature-Request.md'
        - 'Overview/Networking.md'
        - 'Overview/Orchestrators.md'
        - 'Overview/IAM-and-SSO.md'
        - 'Overview/Storage.md'
        - 'Overview/Task-Executions.md'
        - 'Overview/Use-Case-Example.md'
    - 'Build':
        - 'Build/Local-Virtualizations.md'
        - 'Build/Raspberry-Pi-Cluster.md'
        - 'Build/Private-Clouds.md'
        - 'Build/Public-Clouds.md'
    - 'Deployment':
        - 'Deployment/Configuration-Options.md'
        - 'Deployment/Customizing.md'
        - 'Deployment/Deployment-Profiles.md'
        - 'Deployment/External-Application-Access.md'
        - 'Deployment/Initial-Setup.md'
        - 'Deployment/Local-Virtualizations.md'
        - 'Deployment/Raspberry-Pi-Cluster.md'
        - 'Deployment/Manual-Provisioning.md'
        - 'Deployment/Minimal-Deployment.md'
        - 'Deployment/Private-Clouds.md'
        - 'Deployment/Provisioning-Flow.md'
        - 'Deployment/Provisioning-Templates.md'
        - 'Deployment/Public-Clouds.md'
        - 'Deployment/Remote-Access.md'
        - 'Deployment/Troubleshooting.md'
        - 'Deployment/User-Management.md'
    - 'Development':
        - 'Development/Adding-a-Solution.md'
        - 'Development/Best-Practices.md'
        - 'Development/Central-Functions.md'
        - 'Development/Contribution-Guidelines.md'
        - 'Development/Debugging.md'
        - 'Development/Releasing.md'
        - 'Development/Solution-Metadata.md'
        - 'Development/Testing.md'
    - 'Prerequisites':
        - 'Prerequisites/OpenStack-Setup.md'

theme:
    logo: assets/images/kxascode_white_logo.png
    favicon: assets/images/favicon.png
    name: material
    palette:
        accent: pink
    font:
        text: "arial, sans-serif"
        code: monospace
    features:
        - navigation.indexes
        - navigation.sections
        - navigation.top
        - navigation.tracking
        - navigation.expand
        - search.highlight
        - search.share
        - search.suggest

markdown_extensions:
    - admonition
    - def_list
    - attr_list
    - pymdownx.extra
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.magiclink
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - toc:
        permalink: true
    - codehilite:
        guess_lang: false

extra_css:
    - assets/css/custom.css
extra_javascript:
    - assets/js/custom.js

plugins:
    - search:
        lang: en
