require 'yaml'
require 'json'

file = File.read('profile-config.json')
profile_config = JSON.parse(file)

profile_config_local_volumes=profile_config['config']['local_volumes']
puts "Profile Config #{profile_config_local_volumes}"

# Get needed capacity for GlusterFS volumes disk size
GLUSTERFS_KUBE_VOLUMES_DISK_SIZE=profile_config['config']['glusterFsDiskSize']

# Calculate needed local disk capacity
NUM_1GB_LOCAL_SIZE=profile_config_local_volumes['one_gb'].to_i * 1
NUM_5GB_LOCAL_SIZE=profile_config_local_volumes['five_gb'].to_i * 5
NUM_10GB_LOCAL_SIZE=profile_config_local_volumes['ten_gb'].to_i * 10
NUM_30GB_LOCAL_SIZE=profile_config_local_volumes['thirty_gb'].to_i * 30
NUM_50GB_LOCAL_SIZE=profile_config_local_volumes['fifty_gb'].to_i * 50

# Calculate disk size needs for requested local volumes configured in profile-config.json
LOCAL_KUBE_VOLUMES_DISK_SIZE=NUM_1GB_LOCAL_SIZE+NUM_5GB_LOCAL_SIZE+NUM_10GB_LOCAL_SIZE+NUM_30GB_LOCAL_SIZE+NUM_50GB_LOCAL_SIZE+1

puts "Local Disk Size: #{LOCAL_KUBE_VOLUMES_DISK_SIZE}GB"
puts "GlusterFS Disk Size: #{GLUSTERFS_KUBE_VOLUMES_DISK_SIZE}GB"

current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = configs['configs']

ENVIRONMENT_PREFIX = vagrant_config['environment_prefix']
MAIN_NODE_CPU_CORES = vagrant_config['main_node_cpu_cores']
MAIN_NODE_MEMORY = vagrant_config['main_node_memory']
WORKER_NODE_COUNT = vagrant_config['worker_node_count']
WORKER_NODE_CPU_CORES = vagrant_config['worker_node_cpu_cores']
WORKER_NODE_MEMORY = vagrant_config['worker_node_memory']
DOCKERHUB_USER = vagrant_config['dockerhub_username']
DOCKERHUB_EMAIL = vagrant_config['dockerhub_email']
DOCKERHUB_PASSWORD = vagrant_config['dockerhub_password']
BOX_VERSION = vagrant_config['box_version']

Vagrant.configure("2") do |config|
  config.vm.define "kx.as.code-main" do |subconfig|
    subconfig.vm.box = "kx.as.code-main"
    subconfig.vm.hostname = "kx-main"
    subconfig.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
    subconfig.vm.network :forwarded_port, guest: 22, host: 2230, id: "ssh-kx-main", auto_correct: true
    subconfig.vm.box_url = "V:/jenkins_remote/workspace/VirtualBox/KX.AS.CODE_Main_Build/base-vm/boxes/virtualbox-#{BOX_VERSION}/kx.as.code-main-demo-#{BOX_VERSION}.box"
    subconfig.vm.provision "file", source: "profile-config.json", destination: "/var/tmp/profile-config.json"
    subconfig.vm.provision "file", source: "./users.json", destination: "/var/tmp/users.json"
    Dir[File.dirname(__FILE__) + '/aq*.json'].each do |file|
        file_name = File.basename(file)
        subconfig.vm.provision "file", source: file_name, destination: "/var/tmp/" + file_name
    end
    subconfig.vm.provision "shell", inline: 'sudo mv /var/tmp/aq*.json /usr/share/kx.as.code/workspace/'
    subconfig.vm.provision "shell", inline: "sudo mv /var/tmp/profile-config.json /usr/share/kx.as.code/workspace/"
    subconfig.vm.provision "shell", inline: "cat /usr/share/kx.as.code/workspace/profile-config.json | jq '.'"
    subconfig.vm.provision "shell", inline: 'echo -e "$(date "+%Y-%m-%d_%H%M%S") | KX-Main VM created by Vagrant" | sudo tee /usr/share/kx.as.code/workspace/gogogo'
    subconfig.vm.provision :shell do |s|
      s.inline = "echo -e \"DOCKERHUB_USER=#{DOCKERHUB_USER}\nDOCKERHUB_EMAIL=#{DOCKERHUB_EMAIL}\nDOCKERHUB_PASSWORD=#{DOCKERHUB_PASSWORD}\" | sudo tee /var/tmp/.textfile"
    end
    subconfig.vm.provider "virtualbox" do |v|

      kx_main_local_k8s_storage="#{current_dir}/kx-main-local-k8s-storage.vdi"
      if ARGV[0] == "up" && ! File.exist?(kx_main_local_k8s_storage)
        v.customize [
          'createhd',
          '--filename', kx_main_local_k8s_storage,
          '--format', 'VDI',
           '--size', LOCAL_KUBE_VOLUMES_DISK_SIZE.to_i * 1024
        ]

        v.customize [
          'storageattach', :id,
          '--storagectl', 'SATA Controller',
          '--port', 1, '--device', 0,
          '--type', 'hdd', '--medium',
          kx_main_local_k8s_storage
        ]
      end

      kx_main_glusterfs_k8s_storage="#{current_dir}/kx-main-glusterfs-k8s-storage.vdi"
      if ARGV[0] == "up" && ! File.exist?(kx_main_glusterfs_k8s_storage)
            v.customize [
              'createhd',
              '--filename', kx_main_glusterfs_k8s_storage,
              '--format', 'VDI',
               '--size', GLUSTERFS_KUBE_VOLUMES_DISK_SIZE.to_i * 1024
            ]

            v.customize [
              'storageattach', :id,
              '--storagectl', 'SATA Controller',
              '--port', 2, '--device', 0,
              '--type', 'hdd', '--medium',
              kx_main_glusterfs_k8s_storage
            ]
      end


      v.name = "kx.as.code-#{ENVIRONMENT_PREFIX}-main-#{BOX_VERSION}"
      v.customize ["modifyvm", :id, "--memory", "#{MAIN_NODE_MEMORY}"]
      v.customize ["modifyvm", :id, "--cpus", "#{MAIN_NODE_CPU_CORES}"]
      v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      v.customize ["modifyvm", :id, "--accelerate3d", "off"]
      v.customize ["modifyvm", :id, "--vram", "128"]
      v.customize ["setextradata", :id, "CustomVideoMode1", "1920x1200x32"]
      v.customize ["modifyvm", :id, "--nic1", "nat"]
      v.customize ["modifyvm", :id, "--nic2", "natnetwork","--natnetwork1","kxascode"]
    end
  end

  (1..WORKER_NODE_COUNT).each do |i|
    config.vm.define "kx.as.code-worker#{i}" do |subconfig|
      subconfig.vm.box = "kx.as.code-worker"
      subconfig.vm.hostname = "kx-worker#{i}"
      subconfig.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
      subconfig.vm.network :forwarded_port, guest: 22, host: "223#{i}", id: "ssh-kx-worker#{i}", auto_correct: true
      subconfig.vm.box_url = "V:/jenkins_remote/workspace/VirtualBox/KX.AS.CODE_Worker_Build/base-vm/boxes/virtualbox-#{BOX_VERSION}/kx.as.code-worker-demo-#{BOX_VERSION}.box"
      subconfig.vm.provision "file", source: "profile-config.json", destination: "/var/tmp/profile-config.json"
      subconfig.vm.provision "shell", inline: "sudo mv /var/tmp/profile-config.json /usr/share/kx.as.code/workspace/"
      subconfig.vm.provision "shell", inline: "cat /usr/share/kx.as.code/workspace/profile-config.json | jq '.'"
      subconfig.vm.provision "shell", inline: 'echo -e "$(date "+%Y-%m-%d_%H%M%S") | KX-Worker VM created by Vagrant" | sudo tee /usr/share/kx.as.code/workspace/gogogo'
      subconfig.vm.provider "virtualbox" do |v|

        kx_worker_local_k8s_storage="#{current_dir}/kx-worker#{i}-local-k8s-storage.vdi"
        if ARGV[0] == "up" && ! File.exist?(kx_worker_local_k8s_storage)
          v.customize [
            'createhd',
            '--filename', kx_worker_local_k8s_storage,
            '--format', 'VDI',
             '--size', LOCAL_KUBE_VOLUMES_DISK_SIZE * 1024
          ]

          v.customize [
            'storageattach', :id,
            '--storagectl', 'SATA Controller',
            '--port', 1, '--device', 0,
            '--type', 'hdd', '--medium',
            kx_worker_local_k8s_storage
          ]
        end

        v.name = "kx.as.code-#{ENVIRONMENT_PREFIX}-worker#{i}-#{BOX_VERSION}"
        v.customize ["modifyvm", :id, "--memory", "#{WORKER_NODE_MEMORY}"]
        v.customize ["modifyvm", :id, "--cpus", "#{WORKER_NODE_CPU_CORES}"]
        v.customize ["modifyvm", :id, "--nic1", "nat"]
        v.customize ["modifyvm", :id, "--nic2", "natnetwork","--natnetwork1","kxascode"]
      end
    end
  end
end
