// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspaceFile'](arg1, arg2);
}

export function ExeBuild() {
  return window['go']['main']['App']['ExeBuild']();
}

export function GetCurrentBuildStage() {
  return window['go']['main']['App']['GetCurrentBuildStage']();
}

export function IsVirtualizationToolInstalled(arg1) {
  return window['go']['main']['App']['IsVirtualizationToolInstalled'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SetCurrentBuildStage(arg1) {
  return window['go']['main']['App']['SetCurrentBuildStage'](arg1);
}

export function StopExe() {
  return window['go']['main']['App']['StopExe']();
}

export function UpdateJsonFile(arg1, arg2) {
  return window['go']['main']['App']['UpdateJsonFile'](arg1, arg2);
}
