// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspaceFile(arg1:string,arg2:Error):Promise<void>;

export function ExeBuild():Promise<string>;

export function GetCurrentBuildStage():Promise<string>;

export function IsVirtualizationToolInstalled(arg1:string):Promise<boolean>;

export function OpenURL(arg1:string):Promise<void>;

export function SetCurrentBuildStage(arg1:string):Promise<void>;

export function StopExe():Promise<void>;

export function UpdateJsonFile(arg1:string,arg2:string):Promise<void>;
