configureBindDns() {

echo '''//
// Do any local configuration here
//

// Consider adding the 1918 zones here, if they are not used in your
// organization
//include "/etc/bind/zones.rfc1918";

zone "'${baseDomain}'" {
      type master;
      file "/etc/bind/db.'${baseDomain}'";
      allow-query { any; };
      allow-transfer { '${allowedIpRanges}'; };
};
''' | /usr/bin/sudo tee /etc/bind/named.conf.local

echo '''; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL    86400
$ORIGIN '${baseDomain}'.

@                 IN      SOA	   '${baseDomain}'.   root.'${baseDomain}'. (
            1		; Serial
      604800		; Refresh
        86400		; Retry
      2419200		; Expire
        86400 )	; Negative Cache TTL
;
  IN  NS  ns1.'${baseDomain}'.

@                 IN      A      '${mainIpAddress}'
ns1               IN      A      '${mainIpAddress}'
pgadmin           IN      A      '${mainIpAddress}'
kx-main1          IN      A      '${mainIpAddress}'
ldap              IN      A      '${mainIpAddress}'
ldapadmin         IN      A      '${mainIpAddress}'
rabbitmq          IN      A      '${mainIpAddress}'
remote-desktop    IN      A      '${mainIpAddress}'
api-internal      IN      A      '${mainIpAddress}'
*                 IN      A      '${mainIpAddress}'
''' | /usr/bin/sudo tee /etc/bind/db.${baseDomain}

/usr/bin/sudo named-checkconf
/usr/bin/sudo named-checkzone ${baseDomain} /etc/bind/db.${baseDomain}

}