require 'json'

current_dir    = File.dirname(File.expand_path(__FILE__))

if Vagrant::Util::Platform.windows?
  # Is Windows
  puts "Vagrant launched from windows."
elsif Vagrant::Util::Platform.darwin?
  # Is Mac
  puts "Vagrant launched from mac."
else
  # Assume WSL for now
  puts "Vagrant launched from other system, maybe WSL?"
end

file = File.read('profile-config.json')
profile_config = JSON.parse(file)

profile_config_local_volumes=profile_config['config']['local_volumes']
puts "Profile Config #{profile_config_local_volumes}"

# Get needed capacity for GlusterFS volumes disk size
GLUSTERFS_KUBE_VOLUMES_DISK_SIZE=profile_config['config']['glusterFsDiskSize']

# Calculate needed local disk capacity
NUM_1GB_LOCAL_SIZE=profile_config_local_volumes['one_gb'].to_i * 1
NUM_5GB_LOCAL_SIZE=profile_config_local_volumes['five_gb'].to_i * 5
NUM_10GB_LOCAL_SIZE=profile_config_local_volumes['ten_gb'].to_i * 10
NUM_30GB_LOCAL_SIZE=profile_config_local_volumes['thirty_gb'].to_i * 30
NUM_50GB_LOCAL_SIZE=profile_config_local_volumes['fifty_gb'].to_i * 50

# Calculate disk size needs for requested local volumes configured in profile-config.json
LOCAL_KUBE_VOLUMES_DISK_SIZE=NUM_1GB_LOCAL_SIZE+NUM_5GB_LOCAL_SIZE+NUM_10GB_LOCAL_SIZE+NUM_30GB_LOCAL_SIZE+NUM_50GB_LOCAL_SIZE+1

puts "Local Disk Size: #{LOCAL_KUBE_VOLUMES_DISK_SIZE}GB"
puts "GlusterFS Disk Size: #{GLUSTERFS_KUBE_VOLUMES_DISK_SIZE}GB"

# Environment variables will override the profile-config.json file properties. This was added for the Jenkins jobs, so that they can override parameters
ENVIRONMENT_PREFIX = ENV['environmentPrefix'] || profile_config['config']['vm_properties']['environment_prefix']
puts "ENVIRONMENT_PREFIX: #{ENVIRONMENT_PREFIX}"
MAIN_NODE_CPU_CORES = ENV['mainNodeCpuCores'] || profile_config['config']['vm_properties']['main_node_cpu_cores']
puts "MAIN_NODE_CPU_CORES: #{MAIN_NODE_CPU_CORES}"
MAIN_NODE_MEMORY = ENV['mainNodeMemory'] || profile_config['config']['vm_properties']['main_node_memory']
puts "MAIN_NODE_MEMORY: #{MAIN_NODE_MEMORY}"
WORKER_NODE_COUNT = ENV['workerNodeCount'] || profile_config['config']['vm_properties']['worker_node_count']
puts "WORKER_NODE_COUNT: #{WORKER_NODE_COUNT}"
WORKER_NODE_CPU_CORES = ENV['workerNodeCpuCores'] || profile_config['config']['vm_properties']['worker_node_cpu_cores']
puts "WORKER_NODE_CPU_CORES: #{WORKER_NODE_CPU_CORES}"
WORKER_NODE_MEMORY = ENV['WorkerNodeMemory'] || profile_config['config']['vm_properties']['worker_node_memory']
puts "WORKER_NODE_MEMORY: #{WORKER_NODE_MEMORY}"
DOCKERHUB_USER = ENV['dockerHubUser'] || profile_config['config']['docker']['dockerhub_username']
puts "DOCKERHUB_USER: #{DOCKERHUB_USER}"
DOCKERHUB_EMAIL = ENV['dockerHubEmail'] || profile_config['config']['docker']['dockerhub_email']
puts "DOCKERHUB_EMAIL: #{DOCKERHUB_EMAIL}"
DOCKERHUB_PASSWORD = ENV['DockerHubPassword'] || profile_config['config']['docker']['dockerhub_password']
puts "DOCKERHUB_PASSWORD: #{DOCKERHUB_PASSWORD}"
BOX_VERSION = ENV['boxVersion'] || profile_config['config']['vm_properties']['kx_version']
puts "BOX_VERSION: #{BOX_VERSION}"
KX_SYNC_FOLDER_PATH = ENV['kxSyncFolderPath'] || profile_config['config']['vm_properties']['kx_sync_folder_path']
puts "KX_SYNC_FOLDER_PATH: #{KX_SYNC_FOLDER_PATH}"
KX_MAIN_BOX_LOCATION = ENV['kxMainBoxLocation'] || profile_config['config']['vm_properties']['kx_main_box_location']
puts "KX_MAIN_BOX_LOCATION: #{KX_MAIN_BOX_LOCATION}"
KX_WORKER_BOX_LOCATION = ENV['kxWorkerBoxLocation'] || profile_config['config']['vm_properties']['kx_worker_box_location']
puts "KX_WORKER_BOX_LOCATION: #{KX_WORKER_BOX_LOCATION}"

# VMWare Specific Property for creating additional disks
VMWARE_DISK_UTILITY = ENV['vmWareDiskUtilityPath'] || profile_config['config']['vm_properties']['vmware_disk_utility']
puts "VMWARE_DISK_UTILITY: #{VMWARE_DISK_UTILITY}"

# Create shared folder if it does not exist
if not FileTest::directory?(KX_SYNC_FOLDER_PATH)
  Dir::mkdir(KX_SYNC_FOLDER_PATH)
end

Vagrant.configure("2") do |config|
    config.vm.define "kx.as.code-main" do |subconfig|
        subconfig.vm.box = "kx.as.code-main-vmware-#{BOX_VERSION}"
        subconfig.vm.box_url = KX_MAIN_BOX_LOCATION
        subconfig.vm.synced_folder KX_SYNC_FOLDER_PATH, "/home/kx.hero/KX_Share",
            owner: "kx.hero", group: "kx.hero"
        subconfig.vm.provision "file", source: "profile-config.json", destination: "/var/tmp/profile-config.json"
        subconfig.vm.provision "file", source: "users.json", destination: "/var/tmp/users.json"
        Dir[File.dirname(__FILE__) + '/aq*.json'].each do |file|
            file_name = File.basename(file)
            subconfig.vm.provision "file", source: file_name, destination: "/var/tmp/" + file_name
        end
        subconfig.vm.provision "shell", inline: "hostname -I | awk {'print $1'} | tr -d ' \\t\\n\\r' | sudo tee /vagrant/kx.as.code_main-ip-address"
        subconfig.vm.provision "shell", inline: 'sudo mv /var/tmp/aq*.json /usr/share/kx.as.code/workspace/'
        subconfig.vm.provision "shell", inline: 'sudo mv /var/tmp/users.json /usr/share/kx.as.code/workspace/'
        subconfig.vm.provision "shell", inline: "sudo mv /var/tmp/profile-config.json /usr/share/kx.as.code/workspace/"
        subconfig.vm.provision "shell", inline: "cat /usr/share/kx.as.code/workspace/profile-config.json | jq '.'"
        subconfig.vm.provision "shell", inline: "cat /usr/share/kx.as.code/workspace/users.json | jq '.'"
        subconfig.vm.provision "shell", inline: 'echo -e "$(date "+%Y-%m-%d_%H%M%S") | KX-Main VM created by Vagrant" | sudo tee /usr/share/kx.as.code/workspace/gogogo'
        subconfig.trigger.after :destroy do |trigger|
        trigger.warn = "Destroying VM's disks"
            trigger.run = { :inline => "bash -c 'rm -f kx.as.code_main-ip-address kx-main-local-k8s-storage.vmdk kx-main-glusterfs-k8s-storage.vmdk'" }
        end
        subconfig.vm.provision :shell do |s|
          s.inline = "echo -e \"DOCKERHUB_USER=#{DOCKERHUB_USER}\nDOCKERHUB_EMAIL=#{DOCKERHUB_EMAIL}\nDOCKERHUB_PASSWORD=#{DOCKERHUB_PASSWORD}\" | sudo tee /var/tmp/.textfile"
        end
        subconfig.vm.provider "vmware_desktop" do |v|
            kx_main_local_k8s_storage="#{current_dir}/kx-main-local-k8s-storage.vmdk"
            if Vagrant::Util::Platform.windows?
                kx_main_local_k8s_storage = kx_main_local_k8s_storage.gsub(/\//, '\\')
            end
            if ARGV[0] == "up" && ! File.exist?(kx_main_local_k8s_storage)
              `"#{VMWARE_DISK_UTILITY}" -c -s #{LOCAL_KUBE_VOLUMES_DISK_SIZE}GB -a lsilogic -t 0 #{kx_main_local_k8s_storage}`
            end

            kx_main_glusterfs_k8s_storage="#{current_dir}/kx-main-glusterfs-k8s-storage.vmdk"
            if Vagrant::Util::Platform.windows?
                kx_main_glusterfs_k8s_storage = kx_main_glusterfs_k8s_storage.gsub(/\//, '\\')
            end
            if ARGV[0] == "up" && ! File.exist?(kx_main_glusterfs_k8s_storage)
              `"#{VMWARE_DISK_UTILITY}" -c -s #{GLUSTERFS_KUBE_VOLUMES_DISK_SIZE}GB -a lsilogic -t 0 #{kx_main_glusterfs_k8s_storage}`
            end

            v.gui = true
            v.whitelist_verified = true
            v.vmx['displayname'] = "kx.as.code-#{ENVIRONMENT_PREFIX}-main-#{BOX_VERSION}"
            v.vmx["memsize"] = "#{MAIN_NODE_MEMORY}"
            v.vmx["numvcpus"] = "#{MAIN_NODE_CPU_CORES}"
            v.vmx["mks.enable3d"] = "FALSE"
            v.vmx["ethernet0.pcislotnumber"] = "33"
            v.vmx["sound.startconnected"] = "FALSE"
            v.vmx["sound.present"] = "FALSE"
            v.vmx['scsi0:1.filename'] = kx_main_local_k8s_storage
            v.vmx['scsi0:1.present']  = 'TRUE'
            v.vmx['scsi0:1.redo']     = ''
            v.vmx['scsi0:2.filename'] = kx_main_glusterfs_k8s_storage
            v.vmx['scsi0:2.present']  = 'TRUE'
            v.vmx['scsi0:2.redo']     = ''

        end
    end

    (1..WORKER_NODE_COUNT).each do |i|
        config.vm.define "kx.as.code-worker#{i}" do |subconfig|
          subconfig.vm.box = "kx.as.code-worker-vmware-#{BOX_VERSION}"
          subconfig.vm.box_url = KX_WORKER_BOX_LOCATION
          subconfig.vm.hostname = "kx-worker#{i}"
          subconfig.vm.provision "file", source: "kx.as.code_main-ip-address", destination: "/var/tmp/kx.as.code_main-ip-address"
          subconfig.vm.provision "file", source: "./profile-config.json", destination: "/var/tmp/profile-config.json"
          subconfig.vm.provision "shell", inline: "sudo mv /var/tmp/profile-config.json /usr/share/kx.as.code/workspace/"
          subconfig.vm.provision "shell", inline: "cat /usr/share/kx.as.code/workspace/profile-config.json | jq '.'"
          subconfig.vm.provision "shell", inline: 'echo -e "$(date "+%Y-%m-%d_%H%M%S") | KX-Worker VM created by Vagrant" | sudo tee /usr/share/kx.as.code/workspace/gogogo'
          subconfig.trigger.after :destroy do |trigger|
            trigger.warn = "Destroying VM's disks"
            trigger.run = { :inline => "bash -c 'rm -f kx-worker#{i}-local-k8s-storage.vmdk'" }
          end
          subconfig.vm.provider "vmware_desktop" do |v|

            kx_worker_local_k8s_storage="#{current_dir}/kx-worker#{i}-local-k8s-storage.vmdk"
            if Vagrant::Util::Platform.windows?
                kx_worker_local_k8s_storage = kx_worker_local_k8s_storage.gsub(/\//, '\\')
            end

            if ARGV[0] == "up" && ! File.exist?(kx_worker_local_k8s_storage)
              `"#{VMWARE_DISK_UTILITY}" -c -s #{LOCAL_KUBE_VOLUMES_DISK_SIZE}GB -a lsilogic -t 0 #{kx_worker_local_k8s_storage}`
            end

            v.gui = true
            v.whitelist_verified = true
            v.vmx['displayname'] = "kx.as.code-#{ENVIRONMENT_PREFIX}-worker#{i}-#{BOX_VERSION}"
            v.vmx["memsize"] = "#{WORKER_NODE_MEMORY}"
            v.vmx["numvcpus"] = "#{WORKER_NODE_CPU_CORES}"
            v.vmx["mks.enable3d"] = "FALSE"
            v.vmx["ethernet0.pcislotnumber"] = "33"
            v.vmx["sound.startconnected"] = "FALSE"
            v.vmx["sound.present"] = "FALSE"
            v.vmx['scsi0:1.filename'] = kx_worker_local_k8s_storage
            v.vmx['scsi0:1.present']  = 'TRUE'
            v.vmx['scsi0:1.redo']     = ''

          end
        end
    end
end


  
