variable "ACCESS_KEY" {}
variable "SECRET_KEY" {}
variable "KX_MAIN_AMI_ID" {}
variable "KX_WORKER_AMI_ID" {}
variable "REGION" {}
variable "VPC_CIDR_BLOCK" {}
variable "PRIVATE_ONE_SUBNET_CIDR" {}
variable "PRIVATE_TWO_SUBNET_CIDR" {}
variable "PUBLIC_SUBNET_CIDR" {}
variable "VPN_SUBNET_CIDR" {}
variable "METALLB_FIRST_IP" {}
variable "AVAILABILITY_ZONE" {}
variable "PUBLIC_KEY" {}
variable "VPN_SERVER_CERT_ARN" {}
variable "VPN_CLIENT_CERT_ARN" {}
variable "KX_DOMAIN" {}
variable "NUM_KX_WORKER_NODES" {}
variable "LOCAL_KUBE_VOLUMES_DISK_SIZE" {}
variable "GLUSTERFS_KUBE_VOLUMES_DISK_SIZE" {}
variable "MAIN_INSTANCE_TYPE" {}
variable "WORKER_INSTANCE_TYPE" {}