export const SET_NEXT_VIEW = "SET_NEXT_VIEW";
export const SET_LAST_VIEW = "SET_LAST_VIEW";
export const SET_DEFAULT_VIEW = "SET_DEFAULT_VIEW";
export const SET_GENERAL_CONFIG = "SET_GENERAL_CONFIG";
export const SET_OPTIONAL_CONFIG = "SET_OPTIONAL_CONFIG";
export const SET_NETWORK_CONFIG = "SET_NETWORK_CONFIG";
export const SET_STORAGE_CONFIG = "SET_STORAGE_CONFIG";
export const SET_PRIMARY_COLOR = "SET_PRIMARY_COLOR";